openapi: 3.0.0
info:
  title: ${apigw_name}
  version: 1.0.0

paths:
  /ws/stub:
    x-yc-apigateway-websocket-connect:
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        content:
          '*': ''
  /ws/client:
    x-yc-apigateway-websocket-connect:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${store_fn_id}
        tag: $latest
        service_account_id: ${sa_id}
