openapi: 3.0.0
info:
  title: ${apigw_name}
  version: 1.0.0

paths:
  /ws/stub:
    x-yc-apigateway-websocket-connect:
      summary: WS connections from stub function - just accept
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        content:
          '*': ''
  /ws/client:
    x-yc-apigateway-websocket-connect:
      summary: WS connections from local client - store connection id in db
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${store_fn_id}
        tag: $latest
        service_account_id: ${sa_id}
  /{path+}:
    x-yc-apigateway-any-method:
      summary: HTTP requests to stub function - proxied to local code via WS
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${stub_fn_id}
        tag: $latest
        service_account_id: ${sa_id}
