openapi: 3.0.0
info:
  title: ${apigw_name}
  version: 1.0.0

paths:
  /:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${bridge_fn_id}
        tag: $latest
        service_account_id: ${sa_id}
  /ws:
    x-yc-apigateway-websocket-message:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${bridge_fn_id}
        tag: $latest
        service_account_id: ${sa_id}
